version: 2

vm_settings: &vm_settings
  docker:
    # https://circleci.com/docs/2.0/circleci-images/#nodejs
    - image: circleci/node:latest-browsers
  working_directory: ~/frontend

install_restore_cache: &install_restore_cache
  name: Restore cached dependencies
  keys:
    - dependencies-{{ checksum "yarn.lock" }}
    # Fall back to using the latest cache if no exact match is found
    - dependencies-

install_run: &install_run
  name: Install dependencies with Yarn, purely from the lockfile
  command: yarn install --frozen-lockfile

set_node_version: &set_node_version
  name: Install node@8.11.3 (need right version for `yarn`)
  command: |
    set +e
    touch $BASH_ENV
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
    echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
    echo 'nvm install v8.11.3' >> $BASH_ENV
    echo 'nvm alias default v8.11.3' >> $BASH_ENV

install_save_cache: &install_save_cache
  name: Cache installed dependencies
  paths:
    - ~/.cache/yarn/v1
    - node_modules
  key: dependencies-{{ checksum "yarn.lock" }}

jobs:

  test:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *set_node_version
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Run tests
          # Install libgconf, needed by Cypress' Electron, then run tests
          command: sudo apt-get install libgconf-2-4 && yarn test:ci

      # Store test artifacts
      - store_artifacts:
          path: tests/unit/coverage
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: tests/e2e/screenshots

  build:
    <<: *vm_settings
    steps:
      - checkout

      # Install dependencies
      - restore_cache: *install_restore_cache
      - run: *set_node_version
      - run: *install_run
      - save_cache: *install_save_cache

      - run:
          name: Build for production
          command: yarn build:ci

      # Store build artifacts
      - store_artifacts:
          path: dist

  # deploy:
  #   <<: *vm_settings
  #   steps:
  #     # Install dependencies
  #     - restore_cache: *install_restore_cache
  #     - run: *install_run
  #     - save_cache: *install_save_cache

  #     # Build the app for production
  #     - run: yarn build

  #     ADD YOUR DEPLOYMENT PROCESS HERE
  #     https://circleci.com/docs/2.0/deployment-integrations/

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build
      # - deploy:
      #     # Only deploy if tests pass
      #     requires:
      #       - test
      #     # Only deploy the master branch
      #     filters:
      #       branches:
      #         only: master
