### Queries

query GetSelf {
  self {
    id
    name
    email
  }
}

query GetUser($id: ID!) {
  user(id: $id) {
    id
    name
    email
  }
}

query GetUserContent($id: ID!) {
  userContent(id: $id) {
    ...postFields
    isPublished
  }
}

query GetRecentPosts {
  recentPosts {
    ...postFields
    author {
      id
      name
      email
    }
  }
}

query LocalGetSelf {
  user @client {
    id
    name
    email
  }
}

### Mutations

mutation Authenticate($idToken: String!) {
  authenticate(idToken: $idToken) {
    name
    email
  }
}

mutation CreateDraft($title: String!, $text: String!) {
  createDraft(title: $title, text: $text) {
    ...postFields
    isPublished
  }
}

mutation PublishPost($id: ID!) {
  publishPost(id: $id) {
    ...postFields
    isPublished
  }
}

mutation UpdatePost($id: ID!, $title: String!, $text: String!) {
  updatePost(id: $id, title: $title, text: $text) {
    ...postFields
  }
}

mutation LocalSetSelf($user: User!) {
  setSelf(user: $user) @client
}

### Fragments

fragment postFields on Post {
  id
  title
  text
  updatedAt
  createdAt
}
